language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig python-dev python-nose
script: 
  - scons
notifications:
  irc: "irc.upstandinghackers.com#hammer"
