language: c
compiler:
  - gcc
  - clang
env:
  - BINDINGS=none
matrix:
  include:
    - compiler: gcc
      language: python
      python: "2.7"
      env: BINDINGS=python
    - compiler: clang
      language: python
      python: "2.7"
      env: BINDINGS=python CC=clang
    - compiler: gcc
      language: perl
      perl: "5.18"
      env: BINDINGS=perl
    - compiler: clang
      language: perl
      perl: "5.18"
      env: BINDINGS=perl CC=clang
    - compiler: gcc
      language: perl
      perl: "5.14"
      env: BINDINGS=perl
    - compiler: clang
      language: perl
      perl: "5.14"
      env: BINDINGS=perl CC=clang
    - compiler: gcc
      language: perl
      perl: "5.10"
      env: BINDINGS=perl
    - compiler: clang
      language: perl
      perl: "5.10"
      env: BINDINGS=perl CC=clang
    - compiler: gcc
      language: php
      php: "5.5"
      env: BINDINGS=php
    - compiler: clang
      language: php
      php: "5.5"
      env: BINDINGS=php CC=clang
    - compiler: gcc
      language: php
      php: "5.4"
      env: BINDINGS=php
    - compiler: clang
      language: php
      php: "5.4"
      env: BINDINGS=php CC=clang
before_install:
  - sudo apt-get update -qq
  - if [ "$BINDINGS" != "none" ]; then sudo add-apt-repository ppa:dns/irc -y; sudo apt-get update -qq; sudo apt-get install -qq swig=2.0.8-1irc1~12.04; swig -version; fi
  - if [ "$BINDINGS" == "python" ]; then sudo apt-get install -qq python-dev; fi

install: true
before_script:
  - if [ "$BINDINGS" == "php" ]; then phpenv config-add hammer.ini; fi
script: 
  - scons bindings=$BINDINGS test
notifications:
  irc: 
    channels: 
      - "irc.upstandinghackers.com#hammer"
    use_notice: true
    skip_join: true
        
